exports.seed = function(knex, Promise) {
  const uuidv4 = require('uuid/v4');
  console.log(uuidv4())
  // Deletes ALL existing entries
  return knex('characters').del()
    .then(function() {
      // Inserts seed entries
      return knex('characters').insert([{
          "id": uuidv4(),
          "name": "Obat Al Badaz",
          "race_id": 7,
          "class_id": 2,
          "alignment_id": 6,
          "level": 15,
          "player_id": 1,
          "character_num": 1,
        },
        {
          "id": uuidv4(),
          "name": "Chanos",
          "race_id": 7,
          "class_id": 8,
          "alignment_id": 1,
          "level": 14,
          "player_id": 1,
          "character_num": 2,
        },
        {
          "id": uuidv4(),
          "name": "Barbazel",
          "race_id": 4,
          "class_id": 6,
          "alignment_id": 2,
          "level": 12,
          "player_id": 1,
          "character_num": 3,
        },
        {
          "id": uuidv4(),
          "name": "Muiran",
          "race_id": 1,
          "class_id": 10,
          "alignment_id": 6,
          "level": 11,
          "player_id": 1,
          "character_num": 4,
        },
        {
          "id": uuidv4(),
          "name": "Cort",
          "race_id": 6,
          "class_id": 4,
          "alignment_id": 3,
          "level": 6,
          "player_id": 1,
          "character_num": 5,
        },
        {
          "id": uuidv4(),
          "name": "Garth",
          "race_id": 7,
          "class_id": 4,
          "alignment_id": 5,
          "level": 8,
          "player_id": 1,
          "character_num": 6,
        },
        {
          "id": uuidv4(),
          "name": "Mathishard Forme",
          "race_id": 7,
          "class_id": 2,
          "alignment_id": 3,
          "level": 12,
          "player_id": 1,
          "character_num": 7,
        },
        {
          "id": uuidv4(),
          "name": "Bombax",
          "race_id": 10,
          "class_id": 1,
          "alignment_id": 6,
          "level": 8,
          "player_id": 1,
          "character_num": 8,
        },
        {
          "id": uuidv4(),
          "name": "Jakori Al Badaz",
          "race_id": 7,
          "class_id": 6,
          "alignment_id": 6,
          "level": 8,
          "player_id": 1,
          "character_num": 9,
        },
        {
          "id": uuidv4(),
          "name": "Eina Lightfingers",
          "race_id": 9,
          "class_id": 7,
          "alignment_id": 5,
          "level": 8,
          "player_id": 1,
          "character_num": 10,
        },
        {
          "id": uuidv4(),
          "name": "Lorric Gunderson",
          "race_id": 7,
          "class_id": 3,
          "alignment_id": 5,
          "level": 7,
          "player_id": 1,
          "character_num": 11,
        },
        {
          "id": uuidv4(),
          "name": "Oolish",
          "race_id": 6,
          "class_id": 12,
          "alignment_id": 4,
          "level": 1,
          "player_id": 1,
          "character_num": 12,
        },
        {
          "id": uuidv4(),
          "name": "Teeleh",
          "race_id": 8,
          "class_id": 3,
          "alignment_id": 4,
          "level": 5,
          "player_id": 1,
          "character_num": 13,
        },
        {
          "id": uuidv4(),
          "name": "Arta Myrdhyn",
          "race_id": 7,
          "class_id": 12,
          "alignment_id": 2,
          "level": 5,
          "player_id": 1,
          "character_num": 14,
        }
      ]);
    });
};
